"""empty message

Revision ID: 3b822c2c9977
Revises: bf26fc114428
Create Date: 2022-06-17 13:35:27.221446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b822c2c9977'
down_revision = 'bf26fc114428'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song', sa.Column('genre', sa.String(length=120), nullable=True))
    op.alter_column('song', 'song_link',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('song', 'song_link',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.drop_column('song', 'genre')
    # ### end Alembic commands ###
