"""empty message

Revision ID: bf26fc114428
Revises: 09c0cd8f61b8
Create Date: 2022-06-16 19:07:34.320063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf26fc114428'
down_revision = '09c0cd8f61b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('song', 'genre')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song', sa.Column('genre', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
